# origin Travis CI form https://github.com/JonathanPorta/ci-build

language: objective-c
osx_image: xcode7.3

env:
  matrix:
    - UNITY_VERSION=beta
    - UNITY_VERSION=last
    - UNITY_VERSION=2017.2
    - UNITY_VERSION=2017.1
    - UNITY_VERSION=5.6

matrix:
  allow_failures:
    - env: UNITY_VERSION=beta

before_install:
- chmod -R +x ./Scripts
install:
- travis_wait 50 ./Scripts/install.sh
script:
- ./Scripts/build.sh
