# https://github.com/game-ci/unity-actions

name: Test

on:
  pull_request: {}
  push: {}

# env:
#   UNITY_LICENSE_FILE: UnityLicense/2019.2.11f1.ulf

jobs:
  Test:
    name: Test ${{ matrix.unityVersion }} ${{ matrix.testMode }} ðŸ”‘
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.4.20f1
          - 2020.3.0f1
          - 2021.1.0f1
    steps:
      # Checkout Empty Project
      - name: Checkout Empty Project
        uses: actions/checkout@v2
        with:
          repository: litefeel/UnityEmptyProject

      # Set env
      - name: Set env UNITY_LICENSE_FILE
        run: |
            echo 'UNITY_LICENSE<<EOF' >> $GITHUB_ENV
            cat UnityLicense/${{ matrix.unityVersion }}.ulf >> $GITHUB_ENV
            echo '' >> $GITHUB_ENV
            echo 'EOF' >> $GITHUB_ENV
      # Checkout this project
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
          path: Packages/MyPlugin

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        id: tests
        with:
          customParameters: "-nographics"
          unityVersion: ${{ matrix.unityVersion }}

      # # Build
      # - name: Build project
      #   uses: litefeel/unity-builder@v0.14
      #   with:
      #     unityVersion: ${{ matrix.unityVersion }}
      #     targetPlatform: WebGL

      # Output
      - uses: actions/upload-artifact@v2
        name: Upload tests
        with:
          name: Test results for ${{ matrix.testMode }} on unity ${{ matrix.unityVersion }}
          path: ${{ steps.tests.outputs.artifactsPath }}

      # - uses: actions/upload-artifact@v2
      #   name: Upload build
      #   with:
      #     name: Build
      #     path: build